// Code generated by mockery v1.0.0. DO NOT EDIT.

package order

import mock "github.com/stretchr/testify/mock"

// MockDistanceService is an autogenerated mock type for the DistanceService type
type MockDistanceService struct {
	mock.Mock
}

// Calculate provides a mock function with given fields: start, end
func (_m *MockDistanceService) Calculate(start Location, end Location) (int, error) {
	ret := _m.Called(start, end)

	var r0 int
	if rf, ok := ret.Get(0).(func(Location, Location) int); ok {
		r0 = rf(start, end)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Location, Location) error); ok {
		r1 = rf(start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
